[package]
name = "rust-learning"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-learning"
path = "src/main.rs"

[[bin]]
name = "dijkstra_practice"
path = "src/dijkstra/dijkstra_practice.rs"

[dependencies]
